# A plain disk host: your configuration, a disko layout, and the handful of things a
# configuration cannot state. Everything else — the storage, the machine, the live
# variants, the install recipe, the disk list — is read out of the host itself.
#
# See README.md for where each value comes from, and ../../lib/host-record.nix for the
# record this fills in.
{ pkgs, builder, diskoModule }:

let
  slotName = "secrets";
  # The disk's STABLE identity, taken from the real machine (`ls -l /dev/disk/by-id/`).
  # The install clears exactly the disks the layout names, so a name that moves between
  # boots is a name that can clear the wrong disk.
  device = "/dev/disk/by-id/virtio-main";

  configuration = { modulesPath, ... }: {
    imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];
    system.stateVersion = "26.05";
    boot.loader.grub.enable = false;
    boot.kernelParams = [ "console=ttyS0" ];
    networking.hostName = "example-ext4";
    users.allowNoPasswordLogin = true;
  };

  host = import (pkgs.path + "/nixos/lib/eval-config.nix") {
    system = "x86_64-linux";
    modules = [ configuration diskoModule (import ./layout.nix { inherit device slotName; }) ];
  };
in
builder.lib.imagesFor {
  inherit pkgs host slotName;

  # Runtime paths, read when the phase-2 runner RUNS — on the machine doing the
  # personalizing. Nothing here is a store path, and nothing here is generated by the
  # builder: the age identity comes from `age-keygen`, and the bundle is your sops file,
  # read only to check that the identity being planted belongs to this host.
  secrets = {
    delivery = [ "embedded" "sidecar" ];
    bundle = "/run/secrets/example-ext4/bundle.yaml";
    keyTarget = "/sops.age";
    files = [{
      target = "/sops.age";
      source = "/run/secrets/example-ext4/host.key";
      runtimeSource = "/run/secrets/example-ext4/host.key";
    }];
  };

  # Where the host's identity lands on the installed system. Read from sops-nix when the
  # configuration has it; stated here because this example does not.
  install.keyDestination = "/var/lib/sops/age.key";
}
